name: Build Master
on:
  pull_request:
    types: [closed]
    branches:
      - master
jobs:
  build-master:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.5.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: ${{ matrix.node-version }}

      - name: Create new version
        run: |
          SHA1=${{ github.event.pull_request.head.sha }}
          BRANCH=${{ github.event.pull_request.head.ref }}
          VERSION=1.0.0-${BRANCH}-${SHA1:0:7}
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Commit version
        run: |
          npm version --no-git-tag-version $APP_VERSION

      - name: Install environment
        run: npm ci

      - name: Build
        run: npm run build:ssr
